[package]
authors = ["Genna Wingert"]
categories = ["algorithms"]
description = "SPIR-V compiler for CubeCL"
keywords = ["gpu", "compiler"]
edition = "2021"
license.workspace = true
name = "cubecl-spirv"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/cubecl-spirv"
version.workspace = true

[features]
default = [
  "std",
  "cubecl-common/default",
  "cubecl-core/default",
  "cubecl-runtime/default",
]
std = ["cubecl-common/std", "cubecl-core/std", "cubecl-runtime/std"]

[dependencies]
cubecl-common = { path = "../cubecl-common", version = "0.4.0", default-features = false }
cubecl-core = { path = "../cubecl-core", version = "0.4.0" }
cubecl-runtime = { path = "../cubecl-runtime", version = "0.4.0", default-features = false, features = [
    "channel-mutex",
] }
half = { workspace = true }

hashbrown = { workspace = true }
rspirv = "0.12"

# Optimizer
cubecl-opt = { path = "../cubecl-opt", version = "0.4.0" }
