[package]
edition = "2021"
license.workspace = true
name = "cubecl-spirv"
readme.workspace = true
version.workspace = true

[dependencies]
cubecl-common = { path = "../cubecl-common", version = "0.2.0" }
cubecl-core = { path = "../cubecl-core", version = "0.2.0" }
cubecl-runtime = { path = "../cubecl-runtime", version = "0.2.0", default-features = false, features = [
    "channel-mutex",
] }

hashbrown = { workspace = true }
rspirv = "0.12"

# Optimizer
petgraph = { version = "0.6", features = ["serde-1"] }
serde = { workspace = true }
stable-vec = { version = "0.4" }

[dev-dependencies]
cubecl-linalg = { path = "../cubecl-linalg", version = "0.2.0", features = [
    "export_tests",
] }
cubecl-wgpu = { path = "../cubecl-wgpu", version = "0.2.0" }
