[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = []
description = ""
edition.workspace = true
keywords = ["cuda", "wgpu", "gpgpu", "deep-learning", "machine-learning", "tensor"]
license.workspace = true
name = "cubecl"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl"
version.workspace = true
rust-version = "1.75"

[features]
std = []
doc = []

# Runtimes
wgpu = []
cuda = []
