[package]
edition.workspace = true
license.workspace = true
name = "matmul-example"
readme.workspace = true
version.workspace = true

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn", optional = true, features = [
    "tch",
] }
burn-tensor = { git = "https://github.com/tracel-ai/burn", optional = true }
cubecl = { version = "0.1.0", path = "../../crates/cubecl", features = [
    "linalg",
], optional = true }

[features]
burn-tch-cuda = ["burn"]
cube-cuda = ["cubecl/cuda"]
cube-wgpu = ["cubecl/wgpu"]
