[package]
name = "matmul-example"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
cubecl = { version = "0.1.0", path = "../../crates/cubecl", features = [
    "cuda",
    "linalg",
], optional = true }
burn = { git = "https://github.com/tracel-ai/burn", optional = true, features = ["tch"] }
burn-tensor = { git = "https://github.com/tracel-ai/burn", optional = true }

[features]
burn-tch-cuda = ["burn"]
cube-cuda = ["cubecl"]
