[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "crates/*",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"
readme = "README.md"


[workspace.dependencies]
derive-new = { version = "0.6.0", default-features = false }
log = { default-features = false, version = "0.4.22" }


serde = { version = "1.0.204", default-features = false, features = [
    "derive",
    "alloc",
] } # alloc is for no_std, derive is needed
serde_json = { version = "1.0.119", default-features = false }

dashmap = "5.5.3"
spin = { version = "0.9.8", features = ["mutex", "spin_mutex"] }
hashbrown = "0.14.5"

rand = { version = "0.8.5", default-features = false, features = [
    "std_rng",
] } # std_rng is for no_std
getrandom = { version = "0.2.15", default-features = false }

pollster = "0.3"
dirs = "5.0.1"
web-time = "1.1.0"
md5 = "0.7.0"
async-channel = "2.3"

# Testing
serial_test = "3.1.1"
