[workspace]
# Try
# require version 2 to avoid "feature" additiveness for dev-dependencies
# https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2
resolver = "2"

members = [
    "crates/*",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"
readme = "README.md"


[workspace.dependencies]

spin = { version = "0.9.8", features = ["mutex", "spin_mutex"] }
derive-new = { version = "0.6.0", default-features = false }

serde = { version = "1.0.204", default-features = false, features = [
    "derive",
    "alloc",
] } # alloc is for no_std, derive is needed
dashmap = "5.5.3"
web-time = "1.1.0"
rand = { version = "0.8.5", default-features = false, features = [
    "std_rng",
] } # std_rng is for no_std
getrandom = { version = "0.2.15", default-features = false }

pollster = "0.3"
