compilation_log_level = "Disabled"
autotune_log_level = "Disabled"
autotune_level = "Medium"
profiling_level = "Basic"

[autotune]
logger = { file = "/tmp/autotune.log", stdout = true }

[compilation]
logger = { file = "/tmp/autotune.log" }

[profiling]
logger = { file = "/tmp/profiling.log" }
