[package]
edition = "2021"
license.workspace = true
name = "cubecl-ir"
readme.workspace = true
version.workspace = true

[features]
default = ["serde"]

serde = ["dep:serde"]

[dependencies]
cubecl-common = { path = "../cubecl-common", version = "0.5" }

float-ord = "0.3"
half = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, optional = true, features = ["std", "rc"] }
type_hash = { workspace = true }
smallvec = { workspace = true }