[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "AMD ROCm HIP runtime for CubeCL"
edition.workspace = true
keywords = ["gpu", "amd", "rocm", "hip"]
license.workspace = true
name = "cubecl-hip"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/crates/cubecl-hip"
version.workspace = true

[features]
default = [
    "cubecl-runtime/default",
    "cubecl-common/default",
    "cubecl-core/default",
]
std = ["cubecl-runtime/std", "cubecl-common/std", "cubecl-core/std"]
rocwmma = []
compilation-cache = ["cubecl-common/cache", "serde"]

unit_matmul_tests = ["cubecl-matmul/unit_matmul_tests"]
accelerated_matmul_tests = ["cubecl-matmul/accelerated_matmul_tests"]
matmul_tests = [
    "cubecl-matmul/matmul_tests",
    "unit_matmul_tests",
    "accelerated_matmul_tests",
]
conv_tests = ["cubecl-convolution/conv_tests"]

[dependencies]
cubecl-common = { path = "../cubecl-common", version = "0.6.0" }
cubecl-core = { path = "../cubecl-core", version = "0.6.0", default-features = false }
cubecl-cpp = { path = "../cubecl-cpp", version = "0.6.0", default-features = false, features = [
    "hip",
] }
cubecl-runtime = { path = "../cubecl-runtime", version = "0.6.0", default-features = false, features = [
    "channel-mutex",
] }
cubecl-hip-sys = { version = "6.4.4348200" }

bytemuck = { workspace = true }

derive-new = { workspace = true }
half = { workspace = true }
log = { workspace = true }
paste = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
cubecl-core = { path = "../cubecl-core", version = "0.6.0", features = [
    "export_tests",
] }
cubecl-std = { path = "../cubecl-std", version = "0.6.0", features = [
    "export_tests",
] }
cubecl-matmul = { path = "../cubecl-matmul", version = "0.6.0", features = [
    "export_tests",
] }
cubecl-convolution = { path = "../cubecl-convolution", version = "0.6.0", features = [
    "export_tests",
] }
cubecl-reduce = { path = "../cubecl-reduce", version = "0.6.0", features = [
    "export_tests",
] }
cubecl-random = { path = "../cubecl-random", version = "0.6.0", features = [
    "export_tests",
] }
pretty_assertions = { workspace = true }
