[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "AMD ROCm HIP runtime for CubeCL"
edition.workspace = true
keywords = ["gpu", "amd", "rocm", "hip"]
license.workspace = true
name = "cubecl-hip"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/crates/cubecl-hip"
version.workspace = true

[features]
default = [
  "cubecl-runtime/default",
  "cubecl-common/default",
  "cubecl-core/default",
  "is_hip",
]
std = ["cubecl-runtime/std", "cubecl-common/std", "cubecl-core/std"]
rocwmma = []
is_hip = []

[dependencies]
cubecl-common = { path = "../cubecl-common", version = "0.4.0" }
cubecl-core = { path = "../cubecl-core", version = "0.4.0", default-features = false }
cubecl-cpp = { path = "../cubecl-cpp", version = "0.4.0", default-features = false, features = ["hip"] }
cubecl-runtime = { path = "../cubecl-runtime", version = "0.4.0", default-features = false, features = [
  "channel-mutex",
] }
cubecl-hip-sys = { version = "0.0.7", default-features = false, features = ["rocm_622"] }

bytemuck = { workspace = true }

derive-new = { workspace = true }
half = { workspace = true }
log = { workspace = true }
paste = { workspace = true }

[dev-dependencies]
cubecl-core = { path = "../cubecl-core", version = "0.4.0", features = [
  "export_tests",
] }
cubecl-linalg = { path = "../cubecl-linalg", version = "0.4.0", features = [
  "export_tests",
] }
cubecl-reduce = { path = "../cubecl-reduce", version = "0.4.0", features = [
  "export_tests",
] }
pretty_assertions = { workspace = true }
