[package]
authors = [
    "nathanielsimard <nathaniel.simard.42@gmail.com>",
    "louisfd <louisfd94@gmail.com>",
]
categories = ["science", "mathematics", "algorithms"]
description = "CubeCL core create"
edition.workspace = true
keywords = []
license.workspace = true
name = "cubecl-core"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/cubecl-cube"
version.workspace = true

[features]
default = ["cubecl-runtime/default"]
export_tests = []
std = ["cubecl-runtime/std"]
template = []

[dependencies]
cubecl-common = { path = "../cubecl-common", version = "0.1.1", default-features = false }
cubecl-runtime = { path = "../cubecl-runtime", version = "0.1.1", default-features = false }

bytemuck = { workspace = true }
cubecl-macros = { path = "../cubecl-macros", version = "0.1.1" }
derive-new = { workspace = true }
derive_more = { workspace = true }
half = { workspace = true, features = ["bytemuck"] }
num-traits = { workspace = true }
serde = { workspace = true }

log = { workspace = true }

[dev-dependencies]
trybuild = "1"
