[package]
authors = [
    "nathanielsimard <nathaniel.simard.42@gmail.com>",
    "louisfd <louisfd94@gmail.com>",
]
categories = ["science", "mathematics", "algorithms"]
description = "CubeCL core create"
edition.workspace = true
keywords = []
license.workspace = true
name = "cubecl-core"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/cubecl-cube"
version.workspace = true

[features]
default = []
std = []
template = []
export_tests = []

[dependencies]
cubecl-runtime = { path = "../cubecl-runtime", version = "0.1.0", default-features = false }

bytemuck = { workspace = true }
half = { workspace = true, features = ["bytemuck"] }
serde = { workspace = true }
cubecl-macros = { path = "../cubecl-macros", version = "0.1.0" }
derive-new = { workspace = true }
num-traits = { workspace = true }

log = { workspace = true }

[dev-dependencies]
trybuild = "1"
