[package]
authors = ["Genna Wingert"]
categories = ["algorithms"]
description = "Compiler optimizations for CubeCL"
edition = "2021"
keywords = ["gpu", "compiler"]
license.workspace = true
name = "cubecl-opt"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/cubecl-opt"
version.workspace = true

[features]
default = ["std", "cubecl-common/default", "cubecl-core/default"]
std = ["cubecl-common/std", "cubecl-core/std"]

[dependencies]
cubecl-common = { path = "../cubecl-common", version = "0.5.0", default-features = false }
cubecl-core = { path = "../cubecl-core", version = "0.5.0", default-features = false }
float-ord = "0.3"
log = "0.4"
num = "0.4"
petgraph = { version = "0.6" }
smallvec = { version = "1", features = ["union", "const_generics"] }
stable-vec = { version = "0.4" }
type-map = { version = "0.5" }
