[package]
edition = "2021"
license.workspace = true
name = "cubecl-opt"
readme.workspace = true
version.workspace = true

[dependencies]
cubecl-common = { path = "../cubecl-common", version = "0.2.0" }
cubecl-core = { path = "../cubecl-core", version = "0.2.0" }
petgraph = { version = "0.6" }
stable-vec = { version = "0.4" }
