[package]
edition = "2021"
license.workspace = true
name = "cubecl-opt"
readme.workspace = true
version.workspace = true

[dependencies]
cubecl-common = { path = "../cubecl-common", version = "0.2.0" }
cubecl-core = { path = "../cubecl-core", version = "0.2.0" }
derive_more = { version = "1", features = ["deref", "deref_mut"] }
float-ord = "0.3"
hashlink = "0.9"
num = { version = "0.4" }
petgraph = { version = "0.6" }
stable-vec = { version = "0.4" }
