[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "WGPU runtime for the CubeCL"
edition.workspace = true
keywords = ["gpu", "wgpu", "webgpu", "gpgpu"]
license.workspace = true
name = "cubecl-wgpu"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/crates/cubecl-wgpu"
version.workspace = true

[features]
default = [
    "cubecl-runtime/default",
    "cubecl-common/default",
    "cubecl-core/default",
]
exclusive-memory-only = ["cubecl-runtime/exclusive-memory-only"]
std = ["cubecl-runtime/std", "cubecl-common/std", "cubecl-core/std"]
# 'msl' and 'spirv' features are exclusive
# TODO find a way to have wgpu runtime auto-compiler to support several compilers at the same time
msl = ["cubecl-cpp/metal"]
spirv = ["cubecl-spirv", "ash"]

spirv-dump = ["sanitize-filename"]

[dependencies]
cubecl-common = { path = "../cubecl-common", version = "0.5.0", default-features = false }
cubecl-core = { path = "../cubecl-core", version = "0.5.0", default-features = false }
cubecl-runtime = { path = "../cubecl-runtime", version = "0.5.0", default-features = false, features = [
    "channel-mutex",
] }
derive_more = { workspace = true }
sanitize-filename = { workspace = true, optional = true }

# SPIR-V
ash = { version = "0.38", optional = true }
cubecl-spirv = { path = "../cubecl-spirv", version = "0.5.0", optional = true }

# Metal
cubecl-cpp = { path = "../cubecl-cpp", version = "0.5.0", features = [
    "metal",
], optional = true }

bytemuck = { workspace = true }

async-channel = { workspace = true }
derive-new = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }
web-time = { workspace = true }

cfg-if = { workspace = true }

## wgpu dependency for platforms other than macOS
[target.'cfg(not(target_os = "macos"))'.dependencies]
wgpu = { version = "24.0.3", features = ["fragile-send-sync-non-atomic-wasm"] }
## Uncomment if targeting metal through msl feature
# wgpu = { git = "https://github.com/tracel-ai/wgpu", features = ["fragile-send-sync-non-atomic-wasm"], rev = "624db2ae762b83446693020ae637e2c5879b3af9" }
## For development on wgpu uncomment this one and make it point to your local wgpu repo
# wgpu = { path = "../../../../tracel/wgpu/wgpu", features = ["fragile-send-sync-non-atomic-wasm"]}
## On macOS, the `vulkan-portability` feature is required due to the MoltenVK translation layer.
# To install MoltenVK, install the VulkanSDK: https://vulkan.lunarg.com/sdk/home#mac
[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { version = "24.0.3", features = [
    "vulkan-portability",
    "fragile-send-sync-non-atomic-wasm",
] }
## Uncomment if targeting metal through msl feature
# wgpu = { git = "https://github.com/tracel-ai/wgpu", features = ["vulkan-portability", "fragile-send-sync-non-atomic-wasm"], rev = "624db2ae762b83446693020ae637e2c5879b3af9" }
## For development on wgpu uncomment this one and make it point to your local wgpu repo
# wgpu = { path = "../../../../tracel/wgpu/wgpu", features = ["vulkan-portability", "fragile-send-sync-non-atomic-wasm"]}

[dev-dependencies]
cubecl-core = { path = "../cubecl-core", version = "0.5.0", features = [
    "export_tests",
] }
cubecl-linalg = { path = "../cubecl-linalg", version = "0.5.0", features = [
    "export_tests",
] }
cubecl-reduce = { path = "../cubecl-reduce", version = "0.5.0", features = [
    "export_tests",
] }
half = { workspace = true }
paste = { workspace = true }
pretty_assertions = { workspace = true }

[build-dependencies]
cfg_aliases = "0.2.1"
