[package]
authors = ["nathanielsimard <nathaniel.simard.42@gmail.com>"]
categories = ["science"]
description = "WGPU runtime for the CubeCL"
edition.workspace = true
keywords = ["gpu", "wgpu", "webgpu", "gpgpu"]
license.workspace = true
name = "cubecl-wgpu"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/crates/cubecl-wgpu"
version.workspace = true

[features]
default = [
  "cubecl-runtime/default",
  "cubecl-common/default",
  "cubecl-core/default",
]
std = ["cubecl-runtime/std", "cubecl-common/std", "cubecl-core/std"]

[dependencies]
cubecl-runtime = { path = "../cubecl-runtime", version = "0.1.1", default-features = false, features = [
  "channel-mutex",
] }
cubecl-common = { path = "../cubecl-common", version = "0.1.1" }
cubecl-core = { path = "../cubecl-core", version = "0.1.1" }

bytemuck = { workspace = true }
wgpu = { version = "22.0.0", features = ["fragile-send-sync-non-atomic-wasm"] }
pollster = { workspace = true }

log = { workspace = true }
async-channel = { workspace = true }
derive-new = { workspace = true }
hashbrown = { workspace = true }

[dev-dependencies]
cubecl-core = { path = "../cubecl-core", version = "0.1.1", features = [
  "export_tests",
] }
cubecl-linalg = { path = "../cubecl-linalg", version = "0.1.1", features = [
  "export_tests",
] }
