[package]
authors = [
    "nathanielsimard <nathaniel.simard.42@gmail.com>",
    "louisfd <louisfd94@gmail.com>",
    "maxtremblay <t.maxime@pm.me>"
]
categories = ["science", "mathematics", "algorithms"]
description = "CubeCL Standard Library."
edition.workspace = true
keywords = []
license.workspace = true
name = "cubecl-std"
readme.workspace = true
repository = "https://github.com/tracel-ai/cubecl/tree/main/cubecl-std"
version.workspace = true

[features]
default = [
  "std",
  "cubecl-runtime/default",
  "cubecl-core/default",
]
# export_tests = ["pretty_assertions"]
std = ["cubecl-runtime/std", "cubecl-core/std"]

[dependencies]
# bytemuck = { workspace = true }
cubecl-core = { path = "../cubecl-core", version = "0.4.0", default-features = false }
cubecl-runtime = { path = "../cubecl-runtime", version = "0.4.0", default-features = false }
num-traits = "0.2.19"
# half = { workspace = true, features = ["bytemuck"] }
# pretty_assertions = { workspace = true, optional = true }

# [dev-dependencies]
# trybuild = "1"
