[package]
edition = "2021"
license.workspace = true
name = "cubecl-wgpu-spirv"
readme.workspace = true
version.workspace = true

[features]
default = [
    "cubecl-runtime/default",
    "cubecl-common/default",
    "cubecl-core/default",
]
std = ["cubecl-runtime/std", "cubecl-common/std", "cubecl-core/std"]

[dependencies]
cubecl-common = { path = "../cubecl-common", version = "0.2.0" }
cubecl-core = { path = "../cubecl-core", version = "0.2.0" }
cubecl-runtime = { path = "../cubecl-runtime", version = "0.2.0", default-features = false, features = [
    "channel-mutex",
] }
cubecl-spirv = { path = "../cubecl-spirv", version = "0.2.0" }
cubecl-wgpu = { path = "../cubecl-wgpu", version = "0.2.0" }

bytemuck = { workspace = true }
wgpu = { version = "22.0.0", features = [
    "fragile-send-sync-non-atomic-wasm",
    "spirv",
] }

async-channel = { workspace = true }
derive-new = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }

[dev-dependencies]
cubecl-core = { path = "../cubecl-core", version = "0.2.0", features = [
    "export_tests",
] }
cubecl-linalg = { path = "../cubecl-linalg", version = "0.2.0", features = [
    "export_tests",
] }
pretty_assertions = { workspace = true }

[build-dependencies]
cfg_aliases = "0.2.1"
